# networks:
#   app_network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.0.0/24

services:
  db:
    build: ./db
    container_name: db
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  api:
    container_name: backend
    build: ./backend
    ports:
      - "5174:5174"
    volumes:
      - ./backend:/app

    depends_on:
      - db

    restart: unless-stopped

  web:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app
    restart: unless-stopped

  entry:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"

    depends_on:
      - web
      - api
